### ISSUE TITLE
xkbswitch no -g option

### ISSUE THREAD

**Issue by roachsinai** [rlue/vim-barbaric#10]
Thanks for your work, but I have a question about `g:barbaric_default ` value:

```
" The input method for Normal mode (as defined by `xkbswitch -g` or `ibus engine`)
let g:barbaric_default = 0
```

As described at `xkb-switch` README.md:

```
$ xkb-switch --help

Usage: xkb-switch -s ARG            Sets current layout group to ARG
       xkb-switch -l|--list         Displays all layout groups
       xkb-switch -h|--help         Displays this message
       xkb-switch -v|--version      Shows version number
       xkb-switch -w|--wait [-p]    Waits for group change and exits
       xkb-switch -W                Infinitely waits for group change
       xkb-switch -n|--next         Switch to the next layout group
       xkb-switch [-p]              Displays current layout group
```

how to set `g:barbaric_default`?

**Comment by rlue** [comment]
I don't know why I never got an email notification for this issue. Sorry it comes so late.

It looks like you're looking at [grwlf/xkb-switch](https://github.com/grwlf/xkb-switch), a utility for switching X keyboard layouts (_i.e.,_ on Linux and other UNIX-like systems). This plugin uses [myshov/xkbswitch-macosx](https://github.com/myshov/xkbswitch-macosx), which (as the name implies) is for macOS.

If you're on Linux, this plugin supports only fcitx and ibus IMEs. If you'd like support for other utilities, PRs welcome. :)
