### ISSUE TITLE
switch undefined for 'focus' and 'unfocus' arguments

### ISSUE THREAD

**Issue by jfaure** [rlue/vim-barbaric#11]
autocmd FocusGained * call barbaric#switch('focus')
  autocmd FocusLost   * call barbaric#switch('unfocus')

**Comment by jfaure** [comment]
xiehuc's PR fixes this, pls accept it !

**Comment by rlue** [comment]
Sorry for the delay on this. Don't know why, but I never got an email notification from GitHub on this issue or the PR.

The PR is a step forward, but I still want to do some more intelligent normal/insert mode detection when losing and regaining focus. Will dig into it next week!

**Comment by rlue** [comment]
Actually, I've decided that this vim plugin shouldn't be responsible for managing input method state between windows—that should be the responsibility of the IME (and most IMEs I've used have a config option for this).

If your IME doesn't support per-window state management, I'd be very curious to hear which IME you're using.
