### ISSUE TITLE
add fcitx5 support

### ISSUE THREAD

**Issue by roachsinai** [rlue/vim-barbaric#12]
seems change all `fcitx` to `fcitx5` in file `barbaric.vim` at dir  `autoload` and `plugin` worked.

**Comment by rlue** [comment]
Sorry! I'm not on fcitx5 yet (Debian moves slow). Can you tell me if `fcitx-remote` still works, or has that changed to `fcitx5-remote`, as well?

**Comment by rlue** [comment]
Can you do me a favor and try running off of [this branch](https://github.com/rlue/vim-barbaric/tree/feature/fcitx5-support) and tell me if it works out of the box for you?

**Comment by roachsinai** [comment]
Yeah, it works. Thanks for that update.
