### ISSUE TITLE
Feature Request: always set im as value of g:barbaric_default when enter insert mode

### ISSUE THREAD

**Issue by zyf0330** [rlue/vim-barbaric#13]
I set default im to English, and want to restore im to English when enter insert mode, not last used im.

**Comment by rlue** [comment]
Sorry about the delay! I know it's been a year; unfortunately, I never got an email notification about this issue.

I don't understand. If you want to switch to English when entering Insert mode, why are you using barbaric? Restoring to the last-used IM in insert mode is exactly the purpose of this plugin. :\\

**Comment by zyf0330** [comment]
What I need is just switch to english when enter normal mode, done it by set `g:barbaric_timeout = 0`. So this feature is implemented actually.

**Comment by rlue** [comment]
Clever! I'm glad you found a way to make it work. :)
