### ISSUE TITLE
g:barbaric_default overwritten at launch

### ISSUE THREAD

**Issue by mrzool** [rlue/vim-barbaric#3]
Hello and thanks for this great plugin.

Unfortunately, it doesn't seem to work whenever I start Vim with an input method I don't want to use for normal mode, in my case, German (as opposed to English, which I always want to use in normal mode).

On my system, `xkbswitch -g` outputs `1` when English is set as IM.

Since I cannot be sure I will always have English set as IM when I start Vim, I've put `let g:barbaric_default = 1` in my vimrc.

As I understand it, this should ensure that vim-barbaric always sets my IM to English when I'm in normal mode, but that's not the case: If I start Vim with German set as IM, it just stays that way no matter what.

Am I doing something wrong?

EDIT: `echo g:barbaric_default` returns `0` when I start Vim with German set as IM (it should return `1`), so it seems like something is overwriting that option.

**Comment by rlue** [comment]
The plugin sets 

      let g:barbaric_default = system('xkbswitch -g')

when it's loaded. It sounds like your vimrc (or, at least the line in question) is being sourced before the plugin itself, so it's overwriting the value you've set.

What plugin manager are you using? If there are plugin-manager-specific lines in your vimrc, make sure that those lines come first, and your `let g:barbaric_default` comes after.

**Comment by rlue** [comment]
On second thought, Barbaric really should avoid overwriting the value of `g:barbaric_default` if it's already set, so I've just pushed an update that should address this issue. 

Please try updating the plugin without updating your vimrc and let me know if it works.

**Comment by mrzool** [comment]
> On second thought, Barbaric really should avoid overwriting the value of g:barbaric_default if it's already set

That's how I understood it was supposed to work! 2f7ab0118f5973e1c1f9033204982c5c8ccc6e57 fixes the issue. Thanks for the quick response.
