### ISSUE TITLE
FYI: you should use imactivatefunc and imstatusfunc, iminsert.

### ISSUE THREAD

**Issue by mattn** [rlue/vim-barbaric#5]
Sorry, I'm not user of vim-barbaric. As far as I can see, vim-barbaric use InsertEnter/InsertLeave to switch IME. But vim have imactivatefunc. So if you set iminsert=2, imactivatefunc should be called to activate IME. If you want to know whether IME is activated, you can use imstatusfunc.

**Comment by rlue** [comment]
From the helpdocs:

> ### `:h iminsert`
>
> Specifies whether :lmap or an Input Method (IM) is to be used in Insert mode. Valid values:
> 
> * 0	:lmap is off and IM is off
> * 1	:lmap is ON and IM is off
> * 2	:lmap is off and IM is ON
> 
> **2 is available only when compiled with the +multi_byte_ime, +xim or global-ime.**
>
> ### `:h +multi_byte_ime`
>
> **+multi_byte_ime**	Win32 input method for multibyte chars
>
> ### `:h +xim`
> 
> **+xim**		X input method
> 
> ### `:h global-ime`
>
> WHAT IS GLOBAL IME
> 
> Global IME makes capability to input Chinese, Japanese, and Korean text into Vim buffer on any language version of Windows 98, Windows 95, and Windows NT 4.0.

As of right now, Barbaric is a macOS-only plugin. None of the features above support IM switching on macOS, and the README explicitly states:

> For other platforms, consider:
>
> * built-in support for X11 and MS-Windows IMEs (:help mbyte-XIM / :help mbyte-IME)
> * ...
