### ISSUE TITLE
Having trouble getting it working in Mac OS X 

### ISSUE THREAD

**Issue by thestumbler** [rlue/vim-barbaric#8]
I've tried twice to get Barbaric working, but no joy (system details below).

I have installed [xkbSwitch-macosx](https://github.com/myshov/xkbswitch-macosx) and that seems to work correctly from the command line. But nothing happens as expected when toggling between INSERT and NORMAL mode. For this test, I am staying in the application and the open issue should not apply.  I can also confirm that `barbaric` has been loaded at vim startup.

Any thoughts?

#### System details
* Mac OS X Mojave 10.14.3
* vim 8.1 / macOS version (18 May 2018)

**Comment by TxHawks** [comment]
Same here

**Comment by rlue** [comment]
Whoops, 100% my mistake—I originally built it for mac, but have since moved to Linux, so I didn't have a machine to test my latest changes on.

Should work now, if you update it.

**Comment by thestumbler** [comment]
Thanks!  I can confirm, it works great now.  My fingers thank you.  -Chris
